name: Python CI/CD Pipeline

on: [push]

jobs:
  validate:
    name: Validate code
    runs-on: ubuntu-latest
    timeout-minutes: 5
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
        cache: 'pip'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        [ -f requirements.txt ] && pip install -r requirements.txt
        pip install black flake8 pytest
    
    - name: Check formatting (Black)
      run: black --check --diff .
    
    - name: Lint code (Flake8)
      run: flake8 .
    
    - name: Run tests
      run: pytest -v

  deploy:
    name: Deploy
    needs: validate
    if: success() && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Create deployment
      run: |
        mkdir -p public
        echo "Deployed: $(date)" > public/index.html
        echo "Commit: ${{ github.sha }}" >> public/index.html
    
    - uses: actions/upload-pages-artifact@v1
      with:
        path: 'public'